### ISSUE TITLE
Menu Request

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#45]
I want to be able to create a menu system with interrupts available. I want to use the interrupts to create a complex menu switching routine in Grammer code that will work while the menu routine is ran.

```
Lbl "G->G
FuncG
Repeat getkey(55
getkey->A
//code for graphics
End
.Name+Feild
Menu(0,0,90,"Kalvin(My Name btw)","Option 1","Option 2","Option 3","Option 4"
If this
then that
etc..
End
.Inventory
Menu(0,0,90,"Inventory","Item 1","Item 4","Item 4","Item 4"
If this
then that
etc..
End

.G
If getkey(49
Goto Lbl "Name+Feild
If getkey(53
Goto Lbl "Inventory
End

I realize that there has to be some sort of way to stop the menu routine that is currently on.
Any ideas? 

I could try to make a module that does key emulation to stop the menu when you press on of the desired keys.

**Comment by Zeda** [comment]
Hmm, that will be difficult, but I'll think about it. The `Menu(` command already takes subroutines as arguments (which would be good for dynamic inventory menus for example >_>). It could take another argument for interpreting key presses, I'm just not sure how I would implement it.

As it is, I need to update the menu command to work with custom fonts, so it could be a double update.

**Comment by NonstickAtom785** [comment]
Maybe a separate Menu thing like <sup>o</sup> to setup up the interrupt. Like if a key is press goto a lable. Example.

```
Menu(<sup>o</sup>9,"Lbl Name",49,"Lbl Name
Menu(0,0,54,"Title","Option 1",etc

**Comment by Zeda** [comment]
That would be more difficult; I'd have to use even more ram for a specialized purpose .__.

**Comment by NonstickAtom785** [comment]
Hmm idk then.

**Comment by Zeda** [comment]
(Update from an external chat)

In further discussion, I had mentioned that Grammer's `Menu('` command was based on code I had written for menus that could have multiple headers (for example, you could press left/right to switch to another menu). I didn't expose that functionality and I ended up removing the code for it altogether because I couldn't think of a good way to pass the header number to the subroutine. Well, @NonstickAtom785 pointed out that since Grammer has stack commands, I could simply push the header number to the stack and the subroutines can pop it off that way. I am thinking that it might be worthwhile to:

- Let the `header` argument be a string, or precede it with `'` to indicate that it should call a subroutine to fetch the header.
- Add an optional argument to process `getkey` results

Alternatively, maybe something like `ptr→getKey` can be used to set up a key hook for things like `Menu(` and `Pause`. I could also allow it to work outside of those scenarios, too, but invoking the parser to read `getKey` values (but not `getKey(` values) would be slower when the hook is active. On the other hand, it might make UI easier? I'm not sure, these are just ideas.
