### ISSUE TITLE
Menu( Command

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#5]
I don't know why but on my calc the Menu( command only works sometimes. If there is a `Stop` right after the command it doesn't work, and when I try to make a simple menu say
```
: .0:Return
: Menu(0,0,28,"Choose","Matrix","List
: Stop
```
The stop keeps it from working, I think but when you move the stop down one line then it works but not the right way.
```
: .0:Return
: Menu(0,0,28,"Choose","Matrix","List
: 
: Stop
```
This makes the title "List" and there is only one menu item but it looks like raw data. Hopefully you can help out. Or maybe you fixed it in your latest release.

**Comment by Zeda** [comment]
It turned out to be an issue with the `"` token not properly being parsed as a string terminator. The internal parsing pointer was returned pointing to the end `"`, so then instead of seeing a comma or newline, it went right in to parsing the next string, then the next, and so on, until the `"List` option which didn't have a terminating `"` (since it was the last option), but this was being returned as the header. Now the parser is pointing at the newline token, where it knows there should be at least one option, so why verify that it is a comma? So for the "first" option, it just parses a `Stop` token and exits.

Fun times. Anyways, it is fixed, thanks for finding this!
