### ISSUE TITLE
Omnicalc/Batlib Fonts

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#7]
Code:
```
: .0:Return
: ClrDraw
: Output(3,11+Get("[ALIENFNT              ; Note I also tried "EALIENFNT"
: Text(°"Fix It Please, XD
: Stop
```

**_Doesn't display any kind of readable text._**

**Comment by Zeda** [comment]
Thanks, I was able to fix it! I had not loaded `parsePtr` to `DE`, so when the code went to check for a comma (`$2B`), it didn't find it, so it defaulted to one of the built-in fonts (and they are NOT the right format, hence the gibberish).

One other thing, remember to keep the font in RAM. What I like to do is copy it to a temp program first. For this, you can use `solve(0`, a.k.a. `CopyVar`:
```
Output(3,11+solve(0,"EALIENFNT","Vfnt
```
This copies the font to the temp program named `fnt`, and `solve(0` returns a pointer to the created var. Since you know it is an Omnicalc font, you can copy just the data portion and omit the `11+`. The data size is 1792 bytes:
```
Output(3,solve(0,"EALIENFNT","Vfnt",1792,11
```
